name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Image & file handling
  image_picker: ^1.1.2
  intl: ^0.20.2
  uuid: ^4.5.1
  shared_preferences: ^2.2.3

  # UI
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/backgroundclean.png
    - assets/sample1.jpg
    - assets/sample2.jpg
    - assets/profile.jpg
