name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  image_picker: ^1.2.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  
  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true   # ✅ REQUIRED for Material Icons

  assets:
    - assets/logo.png
    - assets/backgroundclean.png
    - assets/sample1.jpg
    - assets/sample2.jpg
    - assets/profile.jpg
