// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZhab_ZFZ4UHJ2nVO3ZUWDsq8jrP-Qb-w',
    appId: '1:75844601403:web:46ec494f7bb97bd84cbe1e',
    messagingSenderId: '75844601403',
    projectId: 'lost-and-found-b6b6d',
    authDomain: 'lost-and-found-b6b6d.firebaseapp.com',
    storageBucket: 'lost-and-found-b6b6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoV1YdQzq1DiARIy9V6_oSZ9gNwv47_00',
    appId: '1:75844601403:android:956b6a4b1c94bfa34cbe1e',
    messagingSenderId: '75844601403',
    projectId: 'lost-and-found-b6b6d',
    storageBucket: 'lost-and-found-b6b6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS0jlwH7lx4LJuuGTicR185Mjh7cRy6p4',
    appId: '1:75844601403:ios:3fb6ea5463dd02844cbe1e',
    messagingSenderId: '75844601403',
    projectId: 'lost-and-found-b6b6d',
    storageBucket: 'lost-and-found-b6b6d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS0jlwH7lx4LJuuGTicR185Mjh7cRy6p4',
    appId: '1:75844601403:ios:3fb6ea5463dd02844cbe1e',
    messagingSenderId: '75844601403',
    projectId: 'lost-and-found-b6b6d',
    storageBucket: 'lost-and-found-b6b6d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZhab_ZFZ4UHJ2nVO3ZUWDsq8jrP-Qb-w',
    appId: '1:75844601403:web:446f27aebb3b2f424cbe1e',
    messagingSenderId: '75844601403',
    projectId: 'lost-and-found-b6b6d',
    authDomain: 'lost-and-found-b6b6d.firebaseapp.com',
    storageBucket: 'lost-and-found-b6b6d.firebasestorage.app',
  );
}
